### ISSUE TITLE
Can this framework support cubic-bezier functions?

### ISSUE THREAD

**Issue by bill-shuzai** [scottcgi/MojoJS#4]
Recently I've been work on some complicate animation in my project, then I learned this great framework. I know it support fully compatible standard easing effect and more. but I was wonder that if we can customized easing effect by the css props 'transition-timing-function'，input the cubic-bezier function. It might be helpful for developers to  restore the design of the animation.

**Comment by scottcgi** [comment]
These functions `transition-timing-function` and `cubic-bezier` are not supported. 

If you want to support them, you need to extend and implement the easing function like [`animator.easing`](https://github.com/scottcgi/MojoJS-Animation/blob/b51a6ea9f2e143e11c4c29e677b332da429ec6a3/MojoJS.animation.js#L740), and **pass additional params** — because the easing params are standardized and uniform.
